title: "3Diline"
name: "3Diline"
indirizzo: |-
  3Diline

  Via Nazionale delle Puglie 28

  80035 Nola (NA)

  Italia
email: "3diline@tin.it"
tel: "+39 081 512 3280"
description: ""
permalink: /:title/
baseurl: "/3Diline-preview"
url: "https://www.3diline.it"
image: ""
logo: "/assets/Logo.png"
# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed
# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
